const services=[
{name:'Intercâmbio',icon:'↔',desc:'Orientações e demandas de beneficiários de outra Unimed',reasons:['Orientação sobre atendimento de intercâmbio','Pendência no atendimento de intercâmbio','Rede / direcionamento para atendimento','Outro assunto de intercâmbio'],interchangeOnly:true},
{name:'Negociação',icon:'▤',desc:'Mensalidades, débitos e negociação financeira',reasons:['Negociação de débitos','Renegociação de parcelamento','Dúvida sobre cobrança / valores','Quitação / baixa de pagamento'],needsPayment:true,localOnly:true},
{name:'Troca de plano',icon:'↻',desc:'Alterações, migração ou informações do plano',reasons:['Troca ou migração de plano','Inclusão de dependente','Exclusão de dependente','Alteração cadastral'],localOnly:true},
{name:'Autorizações',icon:'✓',desc:'Exames, procedimentos e solicitações',reasons:['Solicitar autorização','Consultar autorização existente','Autorização negada','Enviar documentação']},
{name:'Outros',icon:'…',desc:'Demais dúvidas e solicitações',reasons:['Rede credenciada','Declarações e documentos','Dúvidas gerais','Outro assunto']}
];
const slotGroups=[['08:00','08:20','08:40','09:00','09:20','09:40','10:00','10:20','10:40','11:00','11:20','11:40'],['13:00','13:20','13:40','14:00','14:20','14:40','15:00','15:20','15:40','16:00','16:20','16:40']];
const baseSlots=slotGroups.flat();
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={recipient:'self',origin:'local',method:'card',user:null,service:null,reason:'',payment:'',wantsExtra:false,extraService:null,extraReason:'',date:'',time:'',editingId:null};
const presetOrigin=new URLSearchParams(location.search).get('origem');if(presetOrigin==='intercambio')state.origin='interchange';

function store(){return JSON.parse(localStorage.getItem('semfila_bookings_v8')||'[]')}
function save(v){localStorage.setItem('semfila_bookings_v8',JSON.stringify(v))}
function show(id,step){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');updateProgress(step);window.scrollTo({top:0,behavior:'smooth'})}
function updateProgress(step){$$('.progress-step').forEach((x,i)=>x.classList.toggle('active',i<step));$$('.progress-connector').forEach((x,i)=>x.classList.toggle('active',i<step-1))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function dateISO(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function brDate(iso){if(!iso)return'—';const[y,m,d]=iso.split('-');return`${d}/${m}/${y}`}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatCard(v){const d=v.replace(/\D/g,'').slice(0,17);let o=d.slice(0,4);if(d.length>4)o+='.'+d.slice(4,8);if(d.length>8)o+='.'+d.slice(8,16);if(d.length>16)o+='-'+d.slice(16);return o}
function formatCPF(v){const d=v.replace(/\D/g,'').slice(0,11);let o=d.slice(0,3);if(d.length>3)o+='.'+d.slice(3,6);if(d.length>6)o+='.'+d.slice(6,9);if(d.length>9)o+='-'+d.slice(9,11);return o}
function ageFromBirth(birth){if(!birth)return null;const b=new Date(birth+'T12:00:00'),n=new Date();let age=n.getFullYear()-b.getFullYear();const md=n.getMonth()-b.getMonth();if(md<0||(md===0&&n.getDate()<b.getDate()))age--;return age}
function ageBand(age){if(age==null)return'—';if(age<18)return'0–17';if(age<30)return'18–29';if(age<45)return'30–44';if(age<60)return'45–59';return'60+'}
function maskIdentity(identity,method){const d=identity.replace(/\D/g,'');return method==='cpf'&&d.length===11?`***.${d.slice(3,6)}.${d.slice(6,9)}-**`:identity}
function availableServices(){return services.filter(s=>state.origin==='interchange'?!s.localOnly:!s.interchangeOnly)}
function durationBlocks(){return state.wantsExtra&&state.extraService?2:1}
function durationMinutes(){return durationBlocks()*20}
function serviceLabel(){return state.wantsExtra&&state.extraService?`${state.service.name} + ${state.extraService.name}`:state.service.name}
function reasonLabel(){return state.wantsExtra&&state.extraService?`${state.reason} | ${state.extraReason}`:state.reason}
function businessDates(n=10){const out=[];let d=new Date();d.setHours(12,0,0,0);while(out.length<n){if(d.getDay()!==0&&d.getDay()!==6)out.push(new Date(d));d.setDate(d.getDate()+1)}return out}
function deterministicOccupied(date,time){const sum=[...date+time].reduce((a,c)=>a+c.charCodeAt(0),0);return sum%7===0||sum%13===0}
function bookingTimes(b){const idx=baseSlots.indexOf(b.time);if(idx<0)return[b.time];const group=slotGroups.find(g=>g.includes(b.time));const gi=group.indexOf(b.time);return group.slice(gi,gi+(b.blocks||1))}
function occupied(date,time){if(deterministicOccupied(date,time))return true;return store().some(b=>b.date===date&&b.status!=='Cancelado'&&bookingTimes(b).includes(time))}
function canStart(date,time){const group=slotGroups.find(g=>g.includes(time));if(!group)return false;const i=group.indexOf(time),blocks=durationBlocks();if(i+blocks>group.length)return false;return group.slice(i,i+blocks).every(t=>!occupied(date,t))}
function bookingDateTime(b){return new Date(`${b.date}T${b.time}:00`)}
function canCancel(b){return bookingDateTime(b).getTime()-Date.now()>=2*60*60*1000}
function protocol(){return'SF-'+String(Date.now()).slice(-9)}

$('#cardNumber').addEventListener('input',e=>e.target.value=formatCard(e.target.value));
$('#cpfNumber').addEventListener('input',e=>e.target.value=formatCPF(e.target.value));
$$('#recipientRow .segmented-btn').forEach(btn=>btn.onclick=()=>{state.recipient=btn.dataset.recipient;$$('#recipientRow .segmented-btn').forEach(x=>x.classList.toggle('selected',x===btn));$('#thirdPartyAlert').classList.toggle('hidden',state.recipient!=='other');validateConsent()});
$$('#originRow .segmented-btn').forEach(btn=>btn.onclick=()=>{state.origin=btn.dataset.origin;$$('#originRow .segmented-btn').forEach(x=>x.classList.toggle('selected',x===btn));$('#originUnimedField').classList.toggle('hidden',state.origin!=='interchange')});
$$('#methodRow .segmented-btn').forEach(btn=>btn.onclick=()=>{state.method=btn.dataset.method;$$('#methodRow .segmented-btn').forEach(x=>x.classList.toggle('selected',x===btn));$('#cardField').classList.toggle('hidden',state.method!=='card');$('#cpfField').classList.toggle('hidden',state.method!=='cpf')});
if(presetOrigin==='intercambio'){$$('#originRow .segmented-btn').forEach(x=>x.classList.toggle('selected',x.dataset.origin==='interchange'));$('#originUnimedField').classList.remove('hidden')}
$('#birthDate').addEventListener('change',()=>{const age=ageFromBirth($('#birthDate').value);$('#minorAlert').classList.toggle('hidden',!(age!==null&&age<18))});
$('#lgpdConsent').addEventListener('change',validateConsent);
function validateConsent(){return state.recipient!=='other'||$('#lgpdConsent').checked}
$('#demoBtn').onclick=()=>{if(state.method==='card')$('#cardNumber').value='0144.4295.00081234-6';else $('#cpfNumber').value='123.456.789-00';$('#birthDate').value='1998-12-29';$('#birthDate').dispatchEvent(new Event('change'));if(state.origin==='interchange')$('#originUnimed').value='Unimed BH'};

function setHeader(){if(state.user){$('#headerUser').textContent=state.user.name.split(' ')[0];$('#myBookingsTop').classList.add('visible')}else{$('#headerUser').textContent='Visitante';$('#myBookingsTop').classList.remove('visible')}}
$('#loginBtn').onclick=()=>{const identity=state.method==='card'?$('#cardNumber').value.trim():$('#cpfNumber').value.trim(),birth=$('#birthDate').value,originUnimed=state.origin==='interchange'?$('#originUnimed').value.trim():'Unimed Divinópolis',digits=identity.replace(/\D/g,'');const valid=state.method==='card'?digits.length>=12:digits.length===11;if(!valid||!birth){toast(`Informe ${state.method==='card'?'a carteirinha':'o CPF'} e a data de nascimento.`);return}if(state.origin==='interchange'&&!originUnimed){toast('Informe a Unimed de origem.');return}if(!validateConsent()){toast('Confirme que está ciente das condições para agendamento por terceiro.');return}const name=digits.includes('00081234')||digits==='12345678900'?'Arthur Peixoto Militão':'Beneficiário identificado';state.user={identity,method:state.method,birth,name,recipient:state.recipient,origin:state.origin,originUnimed,age:ageFromBirth(birth)};localStorage.setItem('semfila_user_v8',JSON.stringify(state.user));setHeader();startSchedule()};
$('#logoutBtn').onclick=()=>{localStorage.removeItem('semfila_user_v8');state.user=null;setHeader();show('screen-identification',1)};

function renderServices(){const box=$('#serviceOptions');box.innerHTML='';availableServices().forEach(s=>{const b=document.createElement('button');b.type='button';b.className='service-card';b.innerHTML=`<span>${s.icon}</span><div><b>${s.name}</b><small>${s.desc}</small></div>`;b.onclick=()=>{state.service=s;state.reason='';state.payment='';$$('.service-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#reasonSelect').innerHTML='<option value="">Selecione um motivo</option>'+s.reasons.map(r=>`<option>${escapeHtml(r)}</option>`).join('');$('#paymentArea').classList.toggle('hidden',!s.needsPayment);$$('.payment-btn').forEach(x=>x.classList.remove('selected'));populateExtra();validateService()};box.appendChild(b)})}
function populateExtra(){const sel=$('#extraServiceSelect');sel.innerHTML='<option value="">Selecione o segundo assunto</option>';if(!state.service)return;availableServices().filter(s=>s.name!==state.service.name).forEach(s=>{const o=document.createElement('option');o.value=s.name;o.textContent=s.name;sel.appendChild(o)});$('#extraReasonSelect').innerHTML='<option value="">Selecione o motivo</option>';state.extraService=null;state.extraReason='';updateDuration()}
function updateDuration(){$('#durationBadge').textContent=durationMinutes()+' min';$('#scheduleDuration').textContent=durationMinutes()+' min'}
function validateService(){const primary=state.service&&state.reason&&(!state.service.needsPayment||state.payment),extra=!state.wantsExtra||(state.extraService&&state.extraReason);$('#toSchedule').disabled=!(primary&&extra)}
$('#reasonSelect').onchange=e=>{state.reason=e.target.value;validateService()};
$$('.payment-btn').forEach(btn=>btn.onclick=()=>{state.payment=btn.dataset.payment;$$('.payment-btn').forEach(x=>x.classList.toggle('selected',x===btn));validateService()});
$$('#extraChoiceRow .segmented-btn').forEach(btn=>btn.onclick=()=>{state.wantsExtra=btn.dataset.extra==='yes';$$('#extraChoiceRow .segmented-btn').forEach(x=>x.classList.toggle('selected',x===btn));$('#extraServiceArea').classList.toggle('hidden',!state.wantsExtra);if(!state.wantsExtra){state.extraService=null;state.extraReason='';$('#extraServiceSelect').value=''}updateDuration();validateService()});
$('#extraServiceSelect').onchange=e=>{state.extraService=availableServices().find(s=>s.name===e.target.value)||null;state.extraReason='';$('#extraReasonSelect').innerHTML='<option value="">Selecione o motivo</option>'+(state.extraService?state.extraService.reasons.map(r=>`<option>${escapeHtml(r)}</option>`).join(''):'');updateDuration();validateService()};
$('#extraReasonSelect').onchange=e=>{state.extraReason=e.target.value;validateService()};
function startSchedule(){state.service=null;state.reason='';state.payment='';state.wantsExtra=false;state.extraService=null;state.extraReason='';state.date='';state.time='';renderServices();$('#reasonSelect').innerHTML='<option value="">Selecione primeiro um assunto</option>';$('#paymentArea').classList.add('hidden');$('#extraServiceArea').classList.add('hidden');$$('#extraChoiceRow .segmented-btn').forEach(x=>x.classList.toggle('selected',x.dataset.extra==='no'));$('#boletoTip').classList.toggle('hidden',state.user.origin==='interchange');$('#interchangeRouting').classList.toggle('hidden',state.user.origin!=='interchange');updateDuration();validateService();show('screen-service',2)}
$('#backToId').onclick=()=>show('screen-identification',1);
$('#toSchedule').onclick=()=>{renderDates();show('screen-schedule',3)};

function renderDates(){const dates=businessDates(10),strip=$('#dateStrip');strip.innerHTML='';if(!state.date)state.date=dateISO(dates[0]);const names=['DOM','SEG','TER','QUA','QUI','SEX','SÁB'],months=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];dates.forEach(d=>{const iso=dateISO(d),b=document.createElement('button');b.type='button';b.className='date-btn'+(state.date===iso?' selected':'');b.innerHTML=`<b>${names[d.getDay()]}</b><strong>${String(d.getDate()).padStart(2,'0')}</strong><small>${months[d.getMonth()]}</small>`;b.onclick=()=>{state.date=iso;state.time='';$$('.date-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderSlots()};strip.appendChild(b)});renderSlots()}
function renderSlots(){const box=$('#slots');box.innerHTML='';$('#toReview').disabled=true;const d=new Date(state.date+'T12:00:00');$('#dateCaption').textContent=`Horários disponíveis para ${d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}`;baseSlots.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='slot-btn';b.textContent=t;if(!canStart(state.date,t)){b.classList.add('occupied');b.disabled=true;b.title='Não há capacidade contínua para todo o atendimento'}else b.onclick=()=>{state.time=t;$$('.slot-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#toReview').disabled=false};box.appendChild(b)})}
$('#backService').onclick=()=>show('screen-service',2);$('#toReview').onclick=()=>{renderSummary('#reviewSummary');show('screen-review',4)};$('#backSchedule').onclick=()=>show('screen-schedule',3);
function renderSummary(target){$(target).innerHTML=[['Beneficiário',state.user.name],['Identificação',maskIdentity(state.user.identity,state.user.method)],['Origem',state.user.origin==='interchange'?state.user.originUnimed:'Unimed Divinópolis'],['Assuntos',serviceLabel()],['Motivos',reasonLabel()],['Pagamento',state.payment||'—'],['Tempo reservado',durationMinutes()+' minutos'],['Data',brDate(state.date)],['Horário',state.time]].map(([a,b])=>`<div class="summary-row"><span>${escapeHtml(a)}</span><b>${escapeHtml(b)}</b></div>`).join('')}
$('#confirmBtn').onclick=()=>{const p=protocol(),booking={id:p,protocol:p,user:state.user.name,identity:state.user.identity,birth:state.user.birth,age:state.user.age,method:state.user.method,recipient:state.user.recipient,origin:state.user.origin,originUnimed:state.user.originUnimed,service:serviceLabel(),sector:(state.wantsExtra&&state.extraService&&state.extraService.sector!==state.service.sector?state.service.sector+' + '+state.extraService.sector:state.service.sector),reason:reasonLabel(),payment:state.payment||'—',date:state.date,time:state.time,status:'Agendado',blocks:durationBlocks(),duration:durationMinutes(),created:new Date().toISOString()};const list=store();list.push(booking);save(list);$('#protocol').textContent=p;renderSummary('#successSummary');show('screen-success',4)};
$('#newSchedule').onclick=startSchedule;$('#goMy').onclick=()=>{renderMy();show('screen-my',4)};$('#myBookingsTop').onclick=()=>{if(!state.user){toast('Identifique-se primeiro.');return}renderMy();show('screen-my',4)};$('#panelTop').onclick=()=>window.location.href='painel.html';$('#backMy').onclick=()=>show(state.user?'screen-service':'screen-identification',state.user?2:1);
function currentBookings(){return state.user?store().filter(b=>b.identity===state.user.identity).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)):[]}
function renderMy(){const box=$('#myAppointments'),list=currentBookings();if(!list.length){box.innerHTML='<div class="empty-state">Nenhum agendamento encontrado.</div>';return}box.innerHTML='';list.forEach(b=>{const card=document.createElement('article');card.className='booking-card';const allowed=canCancel(b)&&b.status!=='Cancelado';card.innerHTML=`<div><span class="booking-status ${b.status==='Cancelado'?'cancelled':''}">${escapeHtml(b.status)}</span><h3>${escapeHtml(b.service)}</h3><p>${escapeHtml(b.reason)}</p><small>${brDate(b.date)} às ${escapeHtml(b.time)} • ${b.duration||20} min • ${escapeHtml(b.protocol)}</small></div><button class="secondary-btn cancel-booking" ${allowed?'':'disabled'}>Cancelar</button>`;card.querySelector('.cancel-booking').onclick=()=>{if(!allowed)return;save(store().map(x=>x.id===b.id?{...x,status:'Cancelado'}:x));renderMy();toast('Agendamento cancelado. A vaga foi liberada.')};box.appendChild(card)})}

const savedUser=JSON.parse(localStorage.getItem('semfila_user_v8')||'null');if(savedUser){state.user=savedUser;state.recipient=savedUser.recipient;state.origin=savedUser.origin;state.method=savedUser.method;setHeader()}else setHeader();
